# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tests

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/*'
    branches: 
      - main
  workflow_dispatch:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6  

    - name: Set up Go environment
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6  

    - name: Set up Go environment
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...